<!doctype HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="/main.css" />
</head>
<body class="bg-slate-50">
<header class="bg-red-500 container mx-auto">
    <h1 class="text-2xl font-bold p-8 text-blue-600">Admin Dashboard</h1>
</header>
<main class="container mx-auto p-8">
    <h2 class="text-xl font-bold">User List</h2>
<%--    <ul>--%>
<%--        @for(user : users)--%>
<%--            <li>${user.username}</li>--%>
<%--        @endfor--%>
<%--    </ul>--%>
</main>
</body>
</html>