<!doctype HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../main/resources/static/main.css" />
    <title>Home</title>
</head>
<body class="bg-slate-50">
<header class="bg-green-500 container mx-auto">
    <h1 class="text-4xl font-bold p-8">Home Page</h1>
</header>
</body>
</html>
